import * as React from "react";
import { cn } from "@/lib/utils";

/**
 * A city's map as a banner, with its name set over it in HTML.
 *
 * Shared by the landing page and every city page so the two cannot drift: the
 * scrim, the type placement and — the part that matters — the OpenStreetMap
 * attribution are defined once. A credit that exists on one banner and not the
 * other is the kind of thing nobody notices until it is a licence problem.
 *
 * The type stays in HTML rather than going into the SVG, which keeps it
 * selectable, translatable and theme-aware, and lets the map underneath be
 * regenerated by `npm run banner` without touching a wordmark.
 */
export function MapBanner({
  src,
  title,
  subtitle,
  className,
  titleClassName,
  heightPx,
}: {
  src: string;
  title: string;
  subtitle?: React.ReactNode;
  /** Height comes from the caller: a landing hero wants more than a page header. */
  className?: string;
  titleClassName?: string;
  /**
   * A driven height, in pixels, for a banner that collapses as the page scrolls.
   * Set on the section rather than the image so the map is cropped from the middle
   * out — it keeps the city centre in view as the strip narrows, where scaling the
   * image would squash it.
   */
  heightPx?: number;
}) {
  // One failed asset should leave the page intact rather than a torn box.
  const [failed, setFailed] = React.useState(false);
  React.useEffect(() => setFailed(false), [src]);

  if (failed) return null;

  const collapsing = heightPx !== undefined;

  return (
    <section
      className="relative isolate w-full overflow-hidden border-b"
      style={collapsing ? { height: heightPx } : undefined}
    >
      <img
        src={src}
        alt=""
        aria-hidden
        onError={() => setFailed(true)}
        className={cn("w-full object-cover object-center", collapsing ? "h-full" : className)}
      />

      {/* Strongest on the left, where the type sits, thinning out so the map is
          still a map. Built from `background` rather than from white, so it
          inverts in dark mode instead of assuming a light page. */}
      <div className="absolute inset-0 bg-gradient-to-r from-background via-background/85 to-background/20" />

      <div className="absolute inset-0">
        <div className="flex h-full flex-col justify-center pl-5 pr-4 sm:pl-8 lg:pl-12">
          <h1 className={cn("font-semibold tracking-tighter", titleClassName)}>{title}</h1>
          {/* Hidden once the strip is too short to hold it, rather than clipped. */}
          {(!collapsing || heightPx! > 90) && subtitle}
        </div>
      </div>

      {/* Bottom-right on a chip, which is where every map puts its attribution —
          and the chip is what keeps it legible, since the map is light in both
          themes while `text-muted-foreground` is not. */}
      <p className="absolute bottom-0 right-0 rounded-tl bg-background/80 px-1.5 py-0.5 text-[0.6rem] text-muted-foreground">
        Map data &copy; OpenStreetMap contributors
      </p>
    </section>
  );
}
